
name: build action

on:
  push:
    branches:
      - 'master'
      - 'develop'


jobs:
  test:
    name: Generate apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ${{ github.workspace }}/app/google-services.json
      - name: apk
        run: bash ./gradlew assembleStagingDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/staging/debug/app-staging-debug.apk
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Below is the apk for commit: ${{ github.event.head_commit.message }}
          document: ${{ github.workspace }}/app/build/outputs/apk/staging/debug/app-staging-debug.apk
