
name: build action

on:
  push:
    branches:
      - 'master'
      - 'develop'


jobs:
  test:
    name: Generate apk
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: apk
      run: bash ./gradlew assembleDebug --stacktrace
